# language
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# host environment
os: "linux"
dist: bionic

# command to install dependencies
install:
  - pip install pipenv
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt

# command to run tests
script:
  - tests/manage.py test  # Execute Django tests

jobs:
  include:
    - stage: pypi release
      script: echo "Deploying to PyPI ..."
      deploy:  # deploy (on tag) to PyPI
        provider: pypi
        username: __token__
        password:
          secure: r8e1zT7bJUitQ1fj7vw+WpuijhcByCA1NkLsDEudf6ZyAmRLQuEB0QuigBM4SvpE7xycR7CWI9UAa+yyxWVmSp9qZyCPL6rwSFmKgOmFHMIwywisK4XhyqIyM+4eY21FKqm8pUm0X8W2u/TbIvZITkp0/tl1ICvB+QSTCPWKnp3/AhVcP2ge0YEQIdOBO9OvcU9eyDy/8WYJKgmbpJxAM8Bsnn5+sGJOk6PUW2+yQpgOYkkHGSXxpGvlJmlRzJlYjj1X/kFqEJ3Qutm0pVmO+aygCMC7ZByFJ6CyD7JHIXIADAihLfX7j3do/MNZRBIfCSPIfPDvkAbzNOZ7jQ+tVptEqAT6YMBLpSbSY+kBvdRSmGSGDC0fyTaThVcnm6RuWlqCM6Pedo6Cnt5b2cqdOQRvHHK5K4KOCWucqVH/zsCtjIltEMU2ATReuLj0KB9dxoCQarFmqDIVc8B3kLVInEPWblO3ayf9LJUtAGOt4Vx203muQG7iSS9QviHpfIVg42j9eA9GcHXlPCJumbdkcV4atn6KEreF/Yqar8xo6G2Nrx/xC7fF+wtAQrTHMwS1i9bVKFODT8ULD1k/3s64F4wyDcINY7gphh7/H9EHiViNjpQXeHKWfVbM+vg1ydxmuGJGYOmB2OuzI6KBO949JUrsGc85p8ft5GWWQnMBScM=
        on:
          tags: true
        distributions: "sdist"
