name: Django Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  job-run-django-app-tests:
    name: Deploy DjangoExampleProject and run its integrated tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Start the minIO container
      - name: Start the minIO container
        run: docker run --name miniotest -p 9000:9000 -d minio/minio server /data
      # Setup Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # Install Dependencies
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          -r
          requirements.txt
      # Setup Django
      - name: Deploy DjangoExampleProject
        run: python manage.py migrate
      # Run Django Tests
      - name: Run Django unit tests
        run: python manage.py test
